comment:
  layout: "header, diff, flags, components"
  
component_management:
  individual_components:
    - component_id: libimgdoc2  # this is an identifier that should not be changed
      name: libimgdoc2 implementation  # this is a display name, and can be changed freely
      paths:
        - libimgdoc2
